name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3

      # Not really used at this point but will be if multiarch/platform builds are required
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image and push into dockerhub
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          file: Dockerfile
          push: true
          tags: dyasny/ltc:latest

      # Scan the image with grype, only fail on "High" and worse. 
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "dyasny/ltc:latest"
          fail-build: true
          severity-cutoff: high

      # Set up TF
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.20

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
          
      - name: Run terraform apply
        run: |
          terraform apply -auto-approve -vars-file nomad_job.tfvars -var mysecret=${{ secrets.MYSECRET }}
